# Generated by Django 5.2.12 on 2026-03-20 10:49

import uuid

from django.db import migrations


SYSTEM_CATEGORIES = [
    "إيجار",
    "كهرباء",
    "ماء",
    "إنترنت",
    "رواتب",
    "صيانة",
    "تسويق",
    "رسوم بنكية",
    "رسوم بوابات دفع",
    "أخرى",
]


def create_default_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model("expenses", "ExpenseCategory")
    for name in SYSTEM_CATEGORIES:
        ExpenseCategory.objects.get_or_create(
            name=name,
            defaults={
                "id": uuid.uuid4(),
                "is_system": True,
                "is_active": True,
            },
        )


def reverse_default_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model("expenses", "ExpenseCategory")
    ExpenseCategory.objects.filter(name__in=SYSTEM_CATEGORIES, is_system=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_default_categories,
            reverse_code=reverse_default_categories,
        ),
    ]
