# Generated by Django 5.2.12 on 2026-03-20 10:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_employee_full_name"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_number", models.CharField(max_length=30, unique=True)),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("invoice_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("partially_returned", "Partially Returned"),
                            ("fully_returned", "Fully Returned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("transfer", "Transfer"),
                            ("card", "Card"),
                            ("store_credit", "Store Credit"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_invoices",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "db_table": "sales_invoices",
                "ordering": ["-invoice_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesInvoiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "avg_cost_snapshot",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_invoice_items",
                        to="inventory.product",
                    ),
                ),
                (
                    "sales_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.salesinvoice",
                    ),
                ),
            ],
            options={
                "db_table": "sales_invoice_items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("return_number", models.CharField(max_length=30, unique=True)),
                ("return_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "refund_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("transfer", "Transfer"),
                            ("store_credit", "Store Credit"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_returns",
                        to="core.employee",
                    ),
                ),
                (
                    "sales_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="sales.salesinvoice",
                    ),
                ),
            ],
            options={
                "db_table": "sales_returns",
                "ordering": ["-return_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesReturnItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "avg_cost_snapshot",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "line_effect_on_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_return_items",
                        to="inventory.product",
                    ),
                ),
                (
                    "sales_invoice_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="sales.salesinvoiceitem",
                    ),
                ),
                (
                    "sales_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.salesreturn",
                    ),
                ),
            ],
            options={
                "db_table": "sales_return_items",
                "ordering": ["created_at"],
            },
        ),
    ]
